### ISSUE TITLE
Issue docker Missing protocol

### ISSUE THREAD

**Issue by weckie** [gamebeast2k/docker_traccar2mqtt#3]
Dear,

I'm getting the following error:

[root@nas traccar2mqtt]# docker-compose up
Recreating traccar2mqtt ... done
Attaching to traccar2mqtt
traccar2mqtt           | /app/node_modules/mqtt/lib/connect/index.js:67
traccar2mqtt           |       throw new Error('Missing protocol')
traccar2mqtt           |       ^
traccar2mqtt           |
traccar2mqtt           | Error: Missing protocol
traccar2mqtt           |     at Object.connect (/app/node_modules/mqtt/lib/connect/index.js:67:13)
traccar2mqtt           |     at Object.<anonymous> (/app/server.js:20:24)
traccar2mqtt           |     at Module._compile (internal/modules/cjs/loader.js:688:30)
traccar2mqtt           |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
traccar2mqtt           |     at Module.load (internal/modules/cjs/loader.js:598:32)
traccar2mqtt           |     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
traccar2mqtt           |     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
traccar2mqtt           |     at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
traccar2mqtt           |     at startup (internal/bootstrap/node.js:285:19)
traccar2mqtt           |     at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
traccar2mqtt exited with code 1

Do you know what i can do ?

kind regards

**Comment by weckie** [comment]
I solved this problem. I removed the "..." in the var.env file.
Now i'm not getting any content on my mqtt broker ...
Any suggestions ?

**Comment by gamebeast2k** [comment]
Hey,

`throw new Error('Missing protocol')`
It looks like a config error.
Have you in your var.env 
`mqtt_host="mqtt://1.2.3.4"`
or 
`mqtt_host="1.2.3.4"`
The second dont work. You need mqtt:// @ the start
